package ${classPath};

<#list importList as import>
import ${import};
</#list>

/**
 * generated by @RabbMapper
 * @since ${.now}
 */
public class ${className}Impl implements ${className} {

<#list methodList as method>
    @Override
    public ${method.returnType} ${method.methodName}(${method.variableType} ${method.variableName}) {
        ${method.returnType} ${method.returnType?uncap_first} = new ${method.returnType}();
<#list method.returnFieldList as returnField>
        ${method.returnType?uncap_first}.set${returnField}(${method.variableName}.get${returnField}());
</#list>
        return ${method.returnType?uncap_first};
    }

</#list>
}